let n1="",n2="",n3="",n4="",n5="",n6=""
let n7="",n8="",n9="",n10="",n11="",n12=""
let n13="",n14="",n15="",n16="",n17="",n18=""
let n19="",n20="",n21="",n22="",n23="",n24="",n25=""
function b1level(){
    const part = document.getElementById('partb1').value
    const task = document.getElementById('taskb1').value
    var ans = document.getElementById('answerer')
    switch (part){
        case '1':
            switch (task){
                case '1':
                    n1="A"
                    n2="B"
                    n3="B"
                    n4="A"
                    n5="B"
                    n6="A"
                    n7="C"
                    n8="C"
                    break
                case '2':
                    n1="A"
                    n2="B"
                    n3="C"
                    n4="A"
                    n5="A"
                    n6="B"
                    n7="A"
                    n8="C"
                    break
                case '3':
                    n1="B"
                    n2="C"
                    n3="A"
                    n4="B"
                    n5="B"
                    n6="A"
                    n7="A"
                    n8="C"
                break
                case '4':
                    n1="B"
                    n2="A"
                    n3="A"
                    n4="B"
                    n5="B"
                    n6="C"
                    n7="C"
                    n8="C"
                break
                case '5':
                    n1="B"
                    n2="B"
                    n3="A"
                    n4="A"
                    n5="C"
                    n6="C"
                    n7="A"
                    n8="A"
                break
                case '6':
                    n1="B"
                    n2="B"
                    n3="A"
                    n4="B"
                    n5="A"
                    n6="C"
                    n7="C"
                    n8="B"
                break
                case '7':
                    n1="A"
                    n2="B"
                    n3="C"
                    n4="B"
                    n5="B"
                    n6="A"
                    n7="A"
                    n8="C"
                break
                case '8':
                    n1="C"
                    n2="A"
                    n3="B"
                    n4="C"
                    n5="B"
                    n6="A"
                    n7="C"
                    n8="A"
                break
                case '9':
                    n1="B"
                    n2="C"
                    n3="A"
                    n4="A"
                    n5="C"
                    n6="A"
                    n7="B"
                    n8="B"
                break
                case '10':
                    n1="B"
                    n2="B"
                    n3="C"
                    n4="A"
                    n5="C"
                    n6="A"
                    n7="B"
                    n8="C"
                break
                case '11':
                    n1="C"
                    n2="B"
                    n3="C"
                    n4="A"
                    n5="C"
                    n6="B"
                    n7="A"
                    n8="B"
                break
                case '12':
                    n1="B"
                    n2="C"
                    n3="C"
                    n4="B"
                    n5="A"
                    n6="B"
                    n7="A"
                    n8="C"
                break
            }
            ans.innerHTML = `1.${n1}, 2.${n2}, 3.${n3}, 4.${n4}, 5.${n5}, 6.${n6}, 7.${n7}, 8.${n8}`
            break
        case '2':
            switch (task){
                    case '1':
                        n1="B"
                        n2="C"
                        n3="D"
                        n4="D"
                        n5="B"
                        n6="C"
                        n7="A"
                        n8="D"
                        break
                    case '2':
                        n1="A"
                        n2="B"
                        n3="B"
                        n4="D"
                        n5="A"
                        n6="A"
                        n7="C"
                        n8="D"
                        break
                    case '3':
                        n1="D"
                        n2="D"
                        n3="A"
                        n4="C"
                        n5="A"
                        n6="B"
                        n7="B"
                        n8="A"
                    break
                    case '4':
                        n1="C"
                        n2="D"
                        n3="A"
                        n4="B"
                        n5="B"
                        n6="D"
                        n7="B"
                        n8="B"
                    break
                    case '5':
                        n1="C"
                        n2="C"
                        n3="A"
                        n4="A"
                        n5="B"
                        n6="A"
                        n7="B"
                        n8="B"
                    break
                    case '6':
                        n1="C"
                        n2="C"
                        n3="B"
                        n4="B"
                        n5="B"
                        n6="C"
                        n7="B"
                        n8="A"
                    break
                    case '7':
                        n1="C"
                        n2="D"
                        n3="B"
                        n4="D"
                        n5="A"
                        n6="D"
                        n7="B"
                        n8="C"
                    break
                    case '8':
                        n1="D"
                        n2="C"
                        n3="D"
                        n4="A"
                        n5="C"
                        n6="C"
                        n7="A"
                        n8="C"
                    break
                    case '9':
                        n1="C"
                        n2="C"
                        n3="B"
                        n4="D"
                        n5="A"
                        n6="B"
                        n7="C"
                        n8="A"
                    break
                    case '10':
                        n1="B"
                        n2="D"
                        n3="B"
                        n4="A"
                        n5="C"
                        n6="A"
                        n7="C"
                        n8="C"
                    break
                    case '11':
                        n1="D"
                        n2="C"
                        n3="A"
                        n4="B"
                        n5="B"
                        n6="A"
                        n7="A"
                        n8="C"
                    break
                    case '12':
                        n1="C"
                        n2="A"
                        n3="D"
                        n4="B"
                        n5="C"
                        n6="A"
                        n7="A"
                        n8="D"
                    break
            }
            ans.innerHTML = `1.${n1}, 2.${n2}, 3.${n3}, 4.${n4}, 5.${n5}, 6.${n6}, 7.${n7}, 8.${n8}`
            break
        case '1.2':
            switch (task){
                case '1':
                    n1="C"
                    n2="A"
                    n3="B"
                    n4="A"
                    n5="C"
                    n6="A"
                    n7="C"
                    n8="B"
                    break
                case '2':
                    n1="B"
                    n2="C"
                    n3="A"
                    n4="C"
                    n5="A"
                    n6="B"
                    n7="C"
                    n8="A"
                    break
                case '3':
                    n1="B"
                    n2="A"
                    n3="B"
                    n4="A"
                    n5="C"
                    n6="A"
                    n7="B"
                    n8="B"
                break
                case '4':
                    n1="B"
                    n2="B"
                    n3="A"
                    n4="A"
                    n5="C"
                    n6="B"
                    n7="C"
                    n8="A"
                break
                case '5':
                    n1="A"
                    n2="C"
                    n3="C"
                    n4="B"
                    n5="C"
                    n6="C"
                    n7="A"
                    n8="A"
                break
                case '6':
                    n1="C"
                    n2="A"
                    n3="C"
                    n4="B"
                    n5="B"
                    n6="A"
                    n7="C"
                    n8="C"
                break
                case '7':
                    n1="B"
                    n2="C"
                    n3="A"
                    n4="B"
                    n5="B"
                    n6="C"
                    n7="A"
                    n8="C"
                break
                case '8':
                    n1="C"
                    n2="A"
                    n3="B"
                    n4="A"
                    n5="A"
                    n6="C"
                    n7="A"
                    n8="B"
                break
                case '9':
                    n1="B"
                    n2="B"
                    n3="C"
                    n4="A"
                    n5="B"
                    n6="A"
                    n7="C"
                    n8="C"
                break
                case '10':
                    n1="A"
                    n2="B"
                    n3="C"
                    n4="A"
                    n5="C"
                    n6="B"
                    n7="C"
                    n8="B"
                break
                case '11':
                    n1="A"
                    n2="C"
                    n3="B"
                    n4="A"
                    n5="B"
                    n6="A"
                    n7="C"
                    n8="B"
                break
                case '12':
                    n1="C"
                    n2="A"
                    n3="B"
                    n4="A"
                    n5="B"
                    n6="C"
                    n7="A"
                    n8="C"
                break
                case '13':
                    n1="C"
                    n2="A"
                    n3="B"
                    n4="C"
                    n5="A"
                    n6="A"
                    n7="C"
                    n8="B"
                break
                case '14':
                    n1="A"
                    n2="C"
                    n3="A"
                    n4="B"
                    n5="C"
                    n6="A"
                    n7="A"
                    n8="C"
                break
                case '15':
                    n1="A"
                    n2="C"
                    n3="B"
                    n4="C"
                    n5="A"
                    n6="C"
                    n7="A"
                    n8="B"
                break
            }
            ans.innerHTML = `1.${n1}, 2.${n2}, 3.${n3}, 4.${n4}, 5.${n5}, 6.${n6}, 7.${n7}, 8.${n8}`
            break
        case '2.2':
            switch (task){
                case '1':
                        n1="C"
                        n2="A"
                        n3="B"
                        n4="A"
                        n5="C"
                        n6="A"
                        n7="C"
                        n8="B"
                        break
                    case '2':
                        n1="B"
                        n2="C"
                        n3="A"
                        n4="C"
                        n5="A"
                        n6="B"
                        n7="C"
                        n8="A"
                        break
                    case '3':
                        n1="B"
                        n2="A"
                        n3="B"
                        n4="A"
                        n5="C"
                        n6="A"
                        n7="B"
                        n8="B"
                    break
                    case '4':
                        n1="B"
                        n2="B"
                        n3="A"
                        n4="A"
                        n5="C"
                        n6="B"
                        n7="C"
                        n8="A"
                    break
                    case '5':
                        n1="A"
                        n2="C"
                        n3="C"
                        n4="B"
                        n5="C"
                        n6="C"
                        n7="A"
                        n8="A"
                    break
                    case '6':
                        n1="C"
                        n2="A"
                        n3="C"
                        n4="B"
                        n5="B"
                        n6="A"
                        n7="C"
                        n8="C"
                    break
                    case '7':
                        n1="B"
                        n2="C"
                        n3="A"
                        n4="B"
                        n5="B"
                        n6="C"
                        n7="A"
                        n8="C"
                    break
                    case '8':
                        n1="C"
                        n2="A"
                        n3="B"
                        n4="A"
                        n5="A"
                        n6="C"
                        n7="A"
                        n8="B"
                    break
                    case '9':
                        n1="B"
                        n2="B"
                        n3="C"
                        n4="A"
                        n5="B"
                        n6="A"
                        n7="C"
                        n8="C"
                    break
                    case '10':
                        n1="A"
                        n2="B"
                        n3="C"
                        n4="A"
                        n5="C"
                        n6="B"
                        n7="C"
                        n8="B"
                    break
                    case '11':
                        n1="A"
                        n2="C"
                        n3="B"
                        n4="A"
                        n5="B"
                        n6="A"
                        n7="C"
                        n8="B"
                    break
                    case '12':
                        n1="C"
                        n2="A"
                        n3="B"
                        n4="A"
                        n5="B"
                        n6="C"
                        n7="A"
                        n8="C"
                    break
                    case '13':
                        n1="C"
                        n2="A"
                        n3="B"
                        n4="C"
                        n5="A"
                        n6="A"
                        n7="C"
                        n8="B"
                    break
                    case '14':
                        n1="A"
                        n2="C"
                        n3="A"
                        n4="B"
                        n5="C"
                        n6="A"
                        n7="A"
                        n8="C"
                    break
                    case '15':
                        n1="A"
                        n2="C"
                        n3="B"
                        n4="C"
                        n5="A"
                        n6="C"
                        n7="A"
                        n8="B"
                    break
                }
                ans.innerHTML = `1.${n1}, 2.${n2}, 3.${n3}, 4.${n4}, 5.${n5}, 6.${n6}, 7.${n7}, 8.${n8}`
                break
        case '1.3':
            switch (task){
                        case '1':
                            n1="B"
                            n2="D"
                            n3="A"
                            n4="C"
                            n5="A"
                            n6="B"
                            n7="A"
                            n8="C"
                            n9="D"
                            n10="C"
                            n11="C"
                            n12="A"
                            n13="C"
                            n14="B"
                            n15="C"
                            n16="C"
                            n17="B"
                            n18="A"
                            n19="D"
                            n20="C"
                            n21="B"
                            n22="C"
                            n23="D"
                            n24="A"
                            n25="B"
                            break
                        case '2':
                            n1="A"
                            n2="D"
                            n3="D"
                            n4="B"
                            n5="C"
                            n6="C"
                            n7="D"
                            n8="D"
                            n9="B"
                            n10="D"
                            n11="A"
                            n12="C"
                            n13="C"
                            n14="D"
                            n15="C"
                            n16="A"
                            n17="A"
                            n18="A"
                            n19="D"
                            n20="A"
                            n21="B"
                            n22="D"
                            n23="C"
                            n24="B"
                            n25="D"
                            break
                        case '3':
                            n1="D"
                            n2="B"
                            n3="A"
                            n4="B"
                            n5="A"
                            n6="A"
                            n7="B"
                            n8="A"
                            n9="D"
                            n10="C"
                            n11="B"
                            n12="C"
                            n13="A"
                            n14="C"
                            n15="C"
                            n16="A"
                            n17="D"
                            n18="B"
                            n19="C"
                            n20="C"
                            n21="C"
                            n22="A"
                            n23="A"
                            n24="C"
                            n25="D"
                            break
                        case '4':
                            n1="D"
                            n2="A"
                            n3="D"
                            n4="D"
                            n5="C"
                            n6="D"
                            n7="A"
                            n8="B"
                            n9="A"
                            n10="A"
                            n11="B"
                            n12="B"
                            n13="D"
                            n14="A"
                            n15="C"
                            n16="A"
                            n17="C"
                            n18="B"
                            n19="B"
                            n20="A"
                            n21="D"
                            n22="C"
                            n23="D"
                            n24="A"
                            n25="C"
                            break
                        case '5':
                            n1="C"
                            n2="A"
                            n3="D"
                            n4="D"
                            n5="B"
                            n6="A"
                            n7="C"
                            n8="C"
                            n9="D"
                            n10="B"
                            n11="C"
                            n12="D"
                            n13="C"
                            n14="D"
                            n15="C"
                            n16="A"
                            n17="A"
                            n18="B"
                            n19="A"
                            n20="C"
                            n21="D"
                            n22="C"
                            n23="D"
                            n24="A"
                            n25="A"
                            break
                        case '6':
                            n1="D"
                            n2="C"
                            n3="B"
                            n4="B"
                            n5="C"
                            n6="A"
                            n7="B"
                            n8="C"
                            n9="A"
                            n10="C"
                            n11="B"
                            n12="D"
                            n13="B"
                            n14="D"
                            n15="B"
                            n16="B"
                            n17="A"
                            n18="A"
                            n19="B"
                            n20="D"
                            n21="A"
                            n22="B"
                            n23="B"
                            n24="D"
                            n25="A"
                            break
                        case '7':
                            n1="A"
                            n2="D"
                            n3="A"
                            n4="D"
                            n5="B"
                            n6="D"
                            n7="A"
                            n8="A"
                            n9="D"
                            n10="C"
                            n11="A"
                            n12="B"
                            n13="A"
                            n14="B"
                            n15="A"
                            n16="B"
                            n17="C"
                            n18="D"
                            n19="A"
                            n20="D"
                            n21="B"
                            n22="A"
                            n23="C"
                            n24="C"
                            n25="A"
                            break
                        case '8':
                            n1="B"
                            n2="A"
                            n3="C"
                            n4="A"
                            n5="B"
                            n6="B"
                            n7="A"
                            n8="D"
                            n9="C"
                            n10="B"
                            n11="A"
                            n12="D"
                            n13="A"
                            n14="B"
                            n15="D"
                            n16="A"
                            n17="D"
                            n18="A"
                            n19="C"
                            n20="B"
                            n21="D"
                            n22="B"
                            n23="A"
                            n24="A"
                            n25="C"
                            break
                        case '9':
                            n1="C"
                            n2="A"
                            n3="B"
                            n4="B"
                            n5="D"
                            n6="B"
                            n7="D"
                            n8="D"
                            n9="B"
                            n10="A"
                            n11="B"
                            n12="D"
                            n13="D"
                            n14="A"
                            n15="C"
                            n16="C"
                            n17="D"
                            n18="A"
                            n19="C"
                            n20="C"
                            n21="B"
                            n22="A"
                            n23="B"
                            n24="C"
                            n25="D"
                            break
                        case '10':
                            n1="B"
                            n2="C"
                            n3="B"
                            n4="C"
                            n5="A"
                            n6="C"
                            n7="A"
                            n8="D"
                            n9="B"
                            n10="A"
                            n11="B"
                            n12="A"
                            n13="C"
                            n14="D"
                            n15="C"
                            n16="A"
                            n17="B"
                            n18="C"
                            n19="B"
                            n20="D"
                            n21="D"
                            n22="A"
                            n23="C"
                            n24="B"
                            n25="A"
                            break
            }
            ans.innerHTML = `1.${n1}, 2.${n2}, 3.${n3}, 4.${n4}, 5.${n5}, 6.${n6}, 7.${n7}, 8.${n8}`
            break
            }
}